# Generated by Django 6.0.6 on 2026-06-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('password', models.CharField(max_length=50, verbose_name='')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
