# Generated by Django 6.0.6 on 2026-06-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
    ]
