# Generated by Django 6.0 on 2026-08-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0011_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
