# Generated by Django 6.0 on 2026-08-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0012_employee_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='createdBy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='updatedBy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
