# Generated by Django 6.0 on 2026-08-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('EmployeeApp', '0013_employee_createdby_employee_updatedby'),
]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='createdBy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='updatedBy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
